---
title: "sloppyplots"
author: "Isabel"
date: "2/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``` {r plots}
library(tidyverse)
library(spotifyr)
corpus <- get_playlist_audio_features("", "6BoVVeeH3vmrHlgivNbefW")
```
# comparing energy levels per album  
``` {r}
corpus_new <- corpus %>%
  group_by(track.album.release_date) %>%
  median_album_energy = median("energy") %>%
  corpus_artist <- summarize(corpus, track.album.artists = "name")
ggplot(corpus_new, aes(x = track.album.name, y = median_album_energy)) +
  geom_col(stat='identity', fill = "#00abff") +
  labs(x = "",
    y = "" ,
    title = "Median energy per album" ,
    subtitle = "",
    caption = "Data source: Spotify API") +
  theme_minimal() +
  theme(
    title = element_text(color = "gray25"),
    plot.caption = element_text(color = "gray25")) +
    coord_flip()
```

```{r compus chromagram}
remotes::install_github('jaburgoyne/compmus')
library(tidyverse)
library(spotifyr)
library(compmus)
ood <-
  get_tidy_audio_analysis("6BoVVeeH3vmrHlgivNbefW") %>%
  select(segments) %>%
  unnest(segments) %>%
  select(start, duration, pitches)
wood %>%
  mutate(pitches = map(pitches, compmus_normalise, "euclidean")) %>%
  compmus_gather_chroma() %>% 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c()
```